### ISSUE TITLE
Test configuration

### ISSUE THREAD

**Issue by spirinvladimir** [spotware/connect-ts-api#22]
- use fix version v2.5.3 for Jasmine
- rename test to spec for use default Jasmine configuration without JASMINE_CONFIG_PATH
- remove JavaScript test runner
- add possibility to run any spec file from spec folder
- rename first spec file spec/connect.test.ts -> spec/connect.ts (_test_ suffix moved to folder name)
- add to .gitignore compiled specs

**Comment by madroneropaulo** [comment]
We need to rewrite the tests on ava.

**Comment by madroneropaulo** [comment]
Tests rewritten to AVA on aa589dc. Closing this for now. Open a new issue with the proper description if needed.
